<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSIT-L-0298" ignored="0" name="HomePage Testing" tests="2" failures="1" timestamp="12 Mar 2018 08:58:19 GMT" time="128.891" errors="0">
  <testcase name="verifyLoginWithInvalidCredentials" time="22.134" classname="com.test.uiautomation.Automation.homePage.TC001_VerifyLoginWithInvalidCredentials"/>
  <testcase name="verifyLoginWithInvalidCredentials" time="22.245" classname="com.test.uiautomation.Automation.homePage.TC001_VerifyLoginWithInvalidCredentials">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.test.uiautomation.Automation.customListner.Listner.onTestSuccess(Listner.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- HomePage Testing -->
